# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  # prevent /boot from filling in
  boot.loader.systemd-boot.configurationLimit = 7;

  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_6_19;

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      options = [ "compress=zstd" "space_cache=v2" "noatime" "ssd" "discard=async" ];
      fsType = "btrfs";
    };

  # TODO: recreate LUKS with --sector-size 4096 to match NVMe native sector size
  # current 512-byte sectors cause read-modify-write amplification
  boot.initrd.luks.devices."encryptedroot" = {
    device = "/dev/nvme0n1p1";
    # bypass dm-crypt workqueues to reduce scheduling overhead on NVMe
    # improves random I/O latency by running encryption inline instead of queuing
    bypassWorkqueues = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
}
