# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  # prevent /boot from filling in
  boot.loader.grub.configurationLimit = 10;

  boot.kernelPackages = lib.mkForce pkgs.linuxPackages_6_16;

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      options = [ "compress=zstd" "space_cache=v2" "noatime" "autodefrag" "ssd" "discard=async" ];
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."encryptedroot".device = "/dev/nvme0n1p1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
}
