name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@ceedf095f4ec1a097402bc6bd80831f2e1a6fde6 # v2.0.0
        with:
          tool-cache: true
          swap-storage: false
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
      - uses: cachix/cachix-action@v17
        with:
          name: domenkozar-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build 
        run: nix build -L
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          cachix push domenkozar-private ./result
          cachix deploy activate --agent cherimoya ./result
